config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about'

  get 'pages/contact'

  get 'pages/how'

  get 'spaceowner' => "listings#spaceowner"
  get 'pages/why'

  resources :listings

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
if Rails.env.development?
	  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/missing.jpg"
	   					validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)

else
  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/missing.jpg",
   					:storage => :dropbox,
   	 				:dropbox_credentials => Rails.root.join("config/dropbox.yml")
 					validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png),
 					:path => ":style/:id_:filename"
 	end

 	 validates :name, :price, :location, :city, presence: true
 	 validates :price, numericality: true

		validates :image, :attachment_presence => true
		validates_with AttachmentPresenceValidator, :attributes => :image
		validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 2.megabytes

		#Listing / User relationship
		belongs_to :user
		end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

       validates :name, presence: true


     # User / listing relationship (when user deleted, listing is deleted too)
       has_many :lisitngs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :configure_permitted_parameters, if: :devise_controller?

	  protected

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) << :name
	    devise_parameter_sanitizer.for(:account_update) << :name

	  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:spaceowner, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

def spaceowner
  @listings = Listing.where(user: current_user).order("created_at DESC")
end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :officetype, :price, :aminities, :city, :location, :rules, :contacts, :image)
    end

    def check_user
        if current_user != @listing.user
        redirect_to root_url, alert: "Sorry!  You are not the owner of this post."
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def how
  end

  def why
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>  Thank you for using Spacez! </p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../">Spacez</a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><% if user_signed_in? %>
           <%= link_to'+ Add a Workspace', new_listing_path %>
      <% end %></li>
        <li><%= link_to "About Spacez!", pages_about_path %></li>
        <li><%= link_to "Contact us", pages_contact_path %> </li>
      </ul>
      


      <ul class="nav navbar-nav navbar-right">

<% if user_signed_in? %>
       <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Your Account<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">

                  <% if user_signed_in? %>
                        <li><%= link_to '+ Add a Workspace', new_listing_path %></li>
                        <li><%= link_to "Manage Workspaces", spaceowner_path %></li>
                  <% else %>
                        <li> <p> Login.  What are you waiting for? </p></li>
                  <% end %>

                  <li class="divider"></li>

                  <li><a href="#">Succcess Stories</a></li>

                  <li class="divider"></li>

                  <% if user_signed_in? %>
                         <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                      
                   <% end %>

                </ul>
              </li>
<% else %>
<li><%= link_to "Get your account", new_user_registration_path %></li>
<li><%= link_to "Log in", new_user_session_path %></li>
 <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spacez</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 
<%= yield %>

<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h4 class="alert alert-danger" role="alert"> These <%= pluralize(@listing.errors.count, "error") %> need to be fixed</h4>
      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :officetype %><br>
    <%= f.text_field :officetype, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :aminities %><br>
    <%= f.text_area :aminities, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
   <%= f.select :city, [['Jeddah','Jeddah'],['Riyadh','Riyadh'],['Dammam','Dammam']], class: "dropdown-menu" %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_area :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rules %><br>
    <%= f.text_area :rules, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contacts %><br>
    <%= f.text_area :contacts, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit a space</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
  <div class="jumbotron">
  <h2>No office, no problem!</h2>
  <p>Find and book available workspaces around you.</p>
</div>


<div class="row">
<div class="col-md-3">
      <% if user_signed_in? %>
           <%= link_to 'Add a Workspace', new_listing_path, class: "btn btn-danger center-block" %>
      <% end %>
    </div>
</div>

<h2> Quick browsing for angry people </h2>
<table class="table table-hover table-bordered table-condensed">
 <tr class = "strong">
    <th class= "h4">Space</th>
    <th class= "h4">Price (per day)</th> 
    <th class= "h4">City</th>
    <th class= "h4">Added By</th>
  </tr>

  <tr>
    <% @listings.each do |listing| %>
    <td class= "h4"><%= link_to listing.name, listing %></td>
    <td><%= number_with_precision(listing.price, precision: 0) %></td>
    <td><%= listing.city %> </td>
    <td><%= listing.user.name %></td> 

  </tr>
  <% end %>
</table>


<br>
<h2> Browse by image </h2>
<div class="row">
</br>
  <% @listings.each do |listing| %>
    <div class="col-md-3">
        <div class="thumbnail">
        <%= link_to image_tag(listing.image.url(:medium) ), listing %>
        </div>

        <div class="caption">
        <h3><span><%= link_to listing.name, listing %></span></h3>
        <p> Add by <strong><%= listing.user.name %></strong>  </p>
        <p> <strong> <%= number_with_precision(listing.price, precision: 0) %> </strong> SAR per workday</p>
        <p><%= listing.city %></p>
      </div>
   </div>
<% end %>
</div>

app/views/listings/new.html.erb
<h1>Add a workspace</h1>
<p> Describe everything :) </P>
<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-6">
    <h1><%= @listing.name %></h1>
       </br>

      <div class="thumbnail">
         <%= image_tag @listing.image.url %>
         </br>

          <%= link_to 'Back', listings_path, class: "btn btn-primary" %>
          <% if (current_user == @listing.user) %>
                    <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-warning" %> 
          <% end %>

    </div>
    </div>
<br/>
    <div class="col-md-6">
      <p><strong>Price:</strong><%= @listing.price %></p>
      <p><%= @listing.officetype %></p>
      <p><strong>Aminities:</strong><%= @listing.aminities %></p>
      <p><%= @listing.city %></p>
      <p><%= @listing.location %></p>
      <p><strong>Rules:</strong><%= @listing.rules %></p>
      <p><strong>Contacts:</strong><%= @listing.contacts %></p>
    </div>

app/views/listings/spaceowner.html.erb
<h1> Your Workspaces </h1>
<div class="row">
</br>
  <% @listings.each do |listing| %>
    <div class="col-md-3">
        <div class="thumbnail">
        <%= link_to image_tag(listing.image.url(:medium)), listing %>
        <div class="caption">
        <h2><%= listing.name %></h2>
        <% if (user_signed_in?) && (current_user == listing.user) %>
          <%= link_to 'Edit', edit_listing_path(listing),  class: "btn btn-link" %>
          <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-link"  %>
          <% end %>
      </div>
     </div>
   </div>
<% end %>
</div>

<div class="row">
<div class="col-md-12">
      <% if user_signed_in? %>
           <%= link_to 'Add a Workspace', new_listing_path, class: "btn btn-danger center-block" %>
      <% end %>
    </div>
</div>
<hr>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/how.html.erb
<h1>Pages#how</h1>
<p>Find me in app/views/pages/how.html.erb</p>

app/views/pages/why.html.erb
<h1>Top 10 reasons to use DeskAt</h1>
<h3 class="alert alert-info" role="alert">Make the best out of your remote hires</h3>
<p>No body likes excuses!   If you hire freelancers and don't want to hear excuses such as (I've had no interent connection, family took over my time, or blah blah blah) to make the best out of your money, you can rent a work space for them during
<br/>
<h3 class="alert alert-info" role="alert"> Make some extra money to cover your office rent and utitily</h3>
<p> Do you know that you can make a good amount of your rent just by renting two desks for 200 SAR a week for each one of them?  Actually, that will make you about 1600 SAR a month which makes 19,200 SAR a year!  That's is just some good easily earned cash.</P> 
<br/>
<h3 class="alert alert-info" role="alert"> Make new friends and find hot talents</h3>
<p> As you know, more and more smart people are starting to work as freelancers.  Mostly, these brilliant people work from home or cafes.  Imagine having a smar....</P> 
<br>